# Generated by Django 6.0.3 on 2026-03-09 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_goals', to='accountability.partnership'),
        ),
    ]
