# Generated by Django 6.0.3 on 2026-03-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0002_goal_partnership'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='penalty',
            field=models.CharField(blank=True, help_text="What's the penalty if you fail?", max_length=255),
        ),
    ]
